FROM node:8-alpine

WORKDIR /app

RUN npm_config_unsafe_perm=true
RUN npm --global config set user root
RUN npm install --global --unsafe-perm ganache-cli

CMD ["ganache-cli","-h","0.0.0.0","-a","100"]
EXPOSE 8545